=== Sign in to your AWS account

. Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions. For details, see Planning the deployment earlier in this guide. 

. Make sure that your AWS account is configured correctly, as discussed in the Technical requirements section.

=== Launch the Quick Start

NOTE: You are responsible for the cost of the AWS services used while running this Quick Start reference deployment. There is no additional cost for using this Quick Start. For full details, see the pricing pages for each AWS service used by this Quick Start. Prices are subject to change.

. Sign in to your AWS account, and launch the following AWS CloudFormation template. 
|===
|[Deploy {partner-product-name} on AWS^]
|===

The deployment takes about {deployment_time} to complete.

[start=2]
. Check the AWS Region that’s displayed in the upper-right corner of the navigation bar, and change it if necessary. This is where the network infrastructure for {partner-product-name} is built. The template is launched in the {default_deployment_region} Region by default.

// *Note:* This deployment includes Amazon Lex and Amazon Kendra, which isn’t currently supported in all AWS Regions. For a current list of supported Regions, see the https://docs.aws.amazon.com/general/latest/gr/elasticfilesystem.html[endpoints and quotas webpage].

[start=3]
. On the *Create stack* page, keep the default setting for the template URL, and then choose *Next*.
. On the *Specify stack details* page, change the stack name if needed. Review the parameters for the template. Provide values for the parameters that require input. For all other parameters, review the default settings and customize them as necessary.


==== Cloudformation Stack Creation Options

Stack can be deployed by creating a new VPC or by using an existing VPC.
 
*Deploy {partner-product-name} into a new VPC (end-to-end deployment)*:

From the deployment S3 Bucket under templates folder select analytics-main.yaml template and copy the object URL for the stack creation.
Fill all the parameters under Parameter Groups:

*	Quickstart Configuration
*	Keywords Function Configuration
*	New VPC Configuration
*	Linux bastion configuration
*	Bastion Host Instance configuration
*	Web App Configuration

*Deploy {partner-product-name} into an existing VPC*:

From the deployment S3 Bucket under templates folder select analytics.yaml template and copy the object URL for the stack creation.
Fill all the parameters under Parameter Groups:

*	Quickstart Configuration
*	Keywords Function Configuration
*	Web App Configuration
*	Web App Deployment Configuration
**	SubnetID1 and SubnetID2 parameters should be given any private subnet under the VPC mentioned in VPCID Parameter.

**	SubnetIDs Parameter has to be given a Comma Separated list of two public subnets under the VPC mentioned in VPCID Parameter.
