AWSTemplateFormatVersion: '2010-09-09'
Description: Creates resources in an existing VPC - Chime Voice Connector audio from KVS,transcribe and publish transcription, keyword-extraction and custom entity extraction results to websocket and DynamoDB table (qs-1re0264ru)
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Parameters to launch stack in an existing VPC"
    OptionalParameters:
      - BastionSecurityGroupId

  AWS::CloudFormation::Interface: 
    ParameterGroups:
        - Label: 
            default: "Quickstart Configuration"
          Parameters: 
            - QSS3BucketName
            - QSTagValue
            - QSS3KeyPrefix
        - Label: 
            default: "Keywords Function Configuration"
          Parameters: 
            - KeywordsFileName
        - Label: 
            default: "Web App Configuration"
          Parameters: 
            - KeyPairName
            - CIDR
            - MinCapacity
            - MaxCapacity
            - DesiredCapacity
            - WebAppInstanceType
        - Label: 
            default: "Web App Deployment Configuration"
          Parameters:            
            - VPCID
            - SubnetID1
            - SubnetID2
            - SubnetIDs
            - BastionSecurityGroupId

    ParameterLabels: 
      QSS3BucketName:
        default: Your configured S3 bucket with all artifacts for the Quickstart.
      QSTagValue:
        default: A tag that will act as an identifier prefix for all assets.
      QSS3KeyPrefix:
        default: The folder name in the artifacts S3 bucket where you want to sync the Git repo.
      KeywordsFileName:
        default: The file name for the keywords function.
      KeyPairName:
        default: The keypair name of the key to ssh into the web app ec2 instances and bastion host.
      VPCID:
        default: The VPC Id for the deployment.
      SubnetID1:
        default: Subnet Id of the Private Subnet for 1st  web-app EC2 instance.
      SubnetID2:
        default: Subnet Id of the Private Subnet for 2nd web-app EC2 instance. 
      SubnetIDs:
        default: Subnet Ids for the application load balancer.
      CIDR:
        default: CIDR to limit the web app access.
      MinCapacity:
        default: Minimum capacity of Web App ASG.
      MaxCapacity:
        default: Maximum capacity of Web App ASG.
      DesiredCapacity:
        default: Desired capacity of Web App ASG.
      BastionSecurityGroupId:
        default: 'The Security Group Id of Bastion Host Instance'
      WebAppInstanceType:
        default: 'Amazon EC2 instance type for the web app instances.'

Parameters:
  QSS3BucketName:
    Description: The S3 bucket created for your copy of Quick Start assets.
    Type: String
    Default: 'aws-quickstart'
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
  QSTagValue:
    Description: 'Tag value to be attached to resource names.'
    Type: String
    Default: 'qs-test'
    MaxLength: 10
    MinLength: 5
  QSS3KeyPrefix:
    Type: String
    Description: 'The S3 key name prefix used for your copy of Quick Start assets.'
    Default: 'quickstart-quantiphi-realtime-analytics/'
    AllowedPattern: ^(?![\/\s])[0-9a-zA-Z-\/]*\/$
  KeywordsFileName:
    AllowedPattern: ^.*.txt$
    Description: 'The file where Keywords are stored for the Keywords Function.'
    Type: String
    Default: 'kw_50_updated.txt'
  KeyPairName:
    Description: 'The name of KeyPair which is used to ssh into EC2 instance.'
    Type: String
    Default: 'quickstart-taskcat'
  VPCID:
    Type: String
    Description: 'VPC ID for deploying web app.'
  SubnetID1: 
    Description: 'Subnet ID for EC2 Instance.'
    Type: String
  SubnetID2: 
    Description: 'Subnet ID for EC2 Instance.'
    Type: String
  SubnetIDs: 
    Description: "Choose the minimum 2 subnets. The availability zone where instance is created should match with atleast one of the subnet's availability zone you choose."
    Type: CommaDelimitedList
  CIDR: 
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Description: 'CIDR to restrict access to web application.'
    Type: String
    Default: "0.0.0.0/0"
  MinCapacity:
    AllowedValues:
      - '1'
      - '2'
      - '3'
      - '4'
    Default: '1'
    Description: 'The minimum number of webapp hosts to be maintained. The minimum number is one.'
    Type: String
  MaxCapacity:
    AllowedValues:
      - '3'
      - '4'
    Default: '4'
    Description: 'The maximum number of webapp hosts to be scaled out. The maximum number is four.'
    Type: String
  DesiredCapacity:
    AllowedValues:
      - '1'
      - '2'
      - '3'
      - '4'
    Default: '2'
    Description: 'The desired number of webapp hosts to create. The maximum number is four.'
    Type: String
  WebAppInstanceType:
    Description: 'Amazon EC2 instance type for the web app instances.'
    Type: String
    Default: 't2.medium'
    AllowedValues:
      - 't2.medium'
      - 't2.large'
      - 't3.medium'
      - 't3.large'
      - 't3.xlarge'
      - 't3.2xlarge'
  BastionSecurityGroupId:
    Type: String
    Description: 'The Security Group Id of Bastion Host Instance.'

Conditions:
  UsingDefaultBucket: 
    Fn::Equals: 
    - !Ref QSS3BucketName
    - 'aws-quickstart'


Resources:
  LambdaFunctionIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - s3.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"

  LambdaFunctionIAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Join
        - ''
        - - !Ref 'LambdaFunctionIAMRole'
          - _policy
      Roles:
      - Ref: LambdaFunctionIAMRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - "logs:CreateLogGroup"
          - "logs:CreateLogStream"
          - "logs:PutLogEvents"
          Resource:
          - arn:aws:logs:*:*:*
        - Effect: Allow
          Action:
          - "s3:GetObject"
          - "s3:GetObjectTagging"
          - "s3:PutObject"
          - "s3:PutObjectTagging"
          - "s3:DeleteObject"
          Resource:
          - "arn:aws:s3:*:*:accesspoint/*"
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref RegionalArtifactBucket
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref RegionalArtifactBucket
              - '/*'
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref QSS3BucketName
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref QSS3BucketName
              - '/*'
        - Effect: Allow
          Action:
          - "iam:GetRole"
          - "iam:PassRole"
          Resource:
          - !GetAtt LambdaFunctionIAMRole.Arn
        - Effect: Allow
          Action:
          - lambda:InvokeFunction
          Resource:
          - "*"
  
  RegionalArtifactBucket:
    Type: AWS::S3::Bucket

  CopyZipsFunction:
    DependsOn:
    - LambdaFunctionIAMPolicy
    Type: AWS::Lambda::Function
    Properties:
      Description: Copies objects from a source S3 bucket to a destination.
      Handler: index.handler
      Runtime: python3.6
      Role: !GetAtt LambdaFunctionIAMRole.Arn
      Timeout: 240
      Code:
        ZipFile: !Join
          - "\n"
          - - import json
            - import logging
            - import threading
            - import boto3
            - import cfnresponse
            - ''
            - 'def copy_objects(source_bucket, dest_bucket, prefix, objects):'
            - '   s3 = boto3.client(''s3'')'
            - '   for o in objects:'
            - '       key = prefix + o'
            - '       copy_source = {'
            - '           ''Bucket'': source_bucket,'
            - '           ''Key'': key'
            - '       }'
            - '       print((''copy_source: %s'' % copy_source))'
            - '       print((''dest_bucket = %s''%dest_bucket))'
            - '       print((''key = %s'' %key))'
            - '       s3.copy_object(CopySource=copy_source, Bucket=dest_bucket,'
            - '             Key=key)'
            - ''
            - 'def delete_objects(bucket, prefix, objects):'
            - '   s3 = boto3.client(''s3'')'
            - '   objects = {''Objects'': [{''Key'': prefix + o} for o in objects]}'
            - '   s3.delete_objects(Bucket=bucket, Delete=objects)'
            - ''
            - 'def timeout(event, context):'
            - '   logging.error(''Execution is about to time out, sending failure
              response to CloudFormation'')'
            - '   cfnresponse.send(event, context, cfnresponse.FAILED, {}, None)'
            - ''
            - 'def handler(event, context):'
            - '   # make sure we send a failure to CloudFormation if the function'
            - '   # is going to timeout'
            - '   timer = threading.Timer((context.get_remaining_time_in_millis()'
            - '             / 1000.00) - 0.5, timeout, args=[event, context])'
            - '   timer.start()'
            - '   print((''Received event: %s'' % json.dumps(event)))'
            - '   status = cfnresponse.SUCCESS'
            - '   try:'
            - '       source_bucket = event[''ResourceProperties''][''SourceBucket'']'
            - '       dest_bucket = event[''ResourceProperties''][''DestBucket'']'
            - '       prefix = event[''ResourceProperties''][''Prefix'']'
            - '       objects = event[''ResourceProperties''][''Objects'']'
            - '       if event[''RequestType''] == ''Delete'':'
            - '           delete_objects(dest_bucket, prefix, objects)'
            - '       else:'
            - '           copy_objects(source_bucket, dest_bucket, prefix, objects)'
            - '   except Exception as e:'
            - '       logging.error(''Exception: %s'' % e, exc_info=True)'
            - '       status = cfnresponse.FAILED'
            - '   finally:'
            - '       timer.cancel()'
            - '       cfnresponse.send(event, context, status, {}, None)'
            - ''
  
  CopyZips:
    Type: Custom::CopyZips
    Properties:
      ServiceToken: !GetAtt 'CopyZipsFunction.Arn'
      DestBucket: !Ref 'RegionalArtifactBucket'
      SourceBucket: !Ref 'QSS3BucketName'
      Prefix: !Ref 'QSS3KeyPrefix'
      Objects:
        - "assets/kw_50_updated.txt"
        - "templates/web-app.yaml"
        - "templates/storage.yaml"
        - "templates/function.yaml"
        - "functions/packages/websocket-connection.zip"
        - "functions/packages/publish-call-metadata.zip"
        - "functions/packages/keyword-extraction.zip"
        - "functions/packages/amazon-chime-recordandtranscribe.zip"
        - "functions/packages/layers/pydub.zip"
        - "functions/packages/layers/pandas.zip"
        - "functions/packages/layers/chimetranscribe-libraries.zip"
        - "functions/packages/layers/date_extractor.zip"
        - "assets/web_app/ui_code.zip"

  StorageStack:
    DependsOn: CopyZips
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL:
        !Sub 
        - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/storage.yaml
        - S3Region: !Ref 'AWS::Region'
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref RegionalArtifactBucket]
      Parameters:
        QSTagValue: !Ref QSTagValue

  LambdaFunctionIAMPolicySourceBucketAccess:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Join
        - ''
        - - !Ref 'LambdaFunctionIAMRole'
          - S3access_policy
      Roles:
      - Ref: LambdaFunctionIAMRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - "s3:GetObject"
          - "s3:GetObjectTagging"
          - "s3:PutObject"
          - "s3:PutObjectTagging"
          - "s3:DeleteObject"
          Resource:
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !GetAtt StorageStack.Outputs.SourceArtifactBucketName
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !GetAtt StorageStack.Outputs.SourceArtifactBucketName
              - '/*'

  CopyAsset:
    DependsOn: LambdaFunctionIAMPolicySourceBucketAccess
    Type: Custom::CopyZips
    Properties:
      ServiceToken: !GetAtt 'CopyZipsFunction.Arn'
      DestBucket: !GetAtt StorageStack.Outputs.SourceArtifactBucketName
      SourceBucket: !Ref 'RegionalArtifactBucket'
      Prefix: !Ref 'QSS3KeyPrefix'
      Objects:
        - "assets/kw_50_updated.txt"

  FunctionsStack:
    DependsOn: CopyZips
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL:
        !Sub 
        - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/function.yaml
        - S3Region: !Ref 'AWS::Region'
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref RegionalArtifactBucket]
      Parameters:
        QSTagValue: !Ref QSTagValue
        QSS3BucketName: 
          Fn::If:
          - UsingDefaultBucket
          - !Sub '${QSS3BucketName}-${AWS::Region}'
          - !Ref RegionalArtifactBucket
        KeywordsFileName: !Ref KeywordsFileName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        RecordingBucketName: !GetAtt StorageStack.Outputs.RecordingBucketName
        MergedRecordingBucketName: !GetAtt StorageStack.Outputs.MergedRecordingBucketName
        SourceArtifactBucketName: !GetAtt StorageStack.Outputs.SourceArtifactBucketName
        TranscriptionWebsocketConnectionTableName: !GetAtt StorageStack.Outputs.TranscriptionWebsocketConnectionTableName
        TranscriptionKeywordExtractionTableName: !GetAtt StorageStack.Outputs.TranscriptionKeywordExtractionTableName
        LiveCallsMetadataTableName: !GetAtt StorageStack.Outputs.LiveCallsMetadataTableName
        LiveCallsTranscriptionTableName: !GetAtt StorageStack.Outputs.LiveCallsTranscriptionTableName
        RecordingBucketARN: !GetAtt StorageStack.Outputs.RecordingBucketARN
        MergedRecordingBucketARN: !GetAtt StorageStack.Outputs.MergedRecordingBucketARN
        SourceArtifactBucketARN: !GetAtt StorageStack.Outputs.SourceArtifactBucketARN
        TranscriptionWebsocketConnectionTableARN: !GetAtt StorageStack.Outputs.TranscriptionWebsocketConnectionTableARN
        TranscriptionKeywordExtractionTableARN: !GetAtt StorageStack.Outputs.TranscriptionKeywordExtractionTableARN
        LiveCallsMetadataTableARN: !GetAtt StorageStack.Outputs.LiveCallsMetadataTableARN
        LiveCallsTranscriptionTableARN: !GetAtt StorageStack.Outputs.LiveCallsTranscriptionTableARN

  WebAppDeploymentStack:
    DependsOn: CopyZips
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL:
        !Sub 
        - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/web-app.yaml
        - S3Region: !Ref 'AWS::Region'
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref RegionalArtifactBucket]
      Parameters:
        QSTagValue: !Ref QSTagValue
        KeyPairName: !Ref KeyPairName
        VPCID: !Ref VPCID
        SubnetID1: !Ref SubnetID1
        SubnetID2: !Ref SubnetID2
        SubnetIDs: 
          Fn::Join:
            - ','
            - !Ref SubnetIDs
        CIDR: !Ref CIDR
        QSS3BucketName: 
          Fn::If:
          - UsingDefaultBucket
          - !Sub '${QSS3BucketName}-${AWS::Region}'
          - !Ref RegionalArtifactBucket
        WebSocketURL : !GetAtt FunctionsStack.Outputs.WebSocketURL 
        WebAppInstanceType: !Ref WebAppInstanceType
        MergedRecordingBucketName: !GetAtt StorageStack.Outputs.MergedRecordingBucketName
        TranscriptionKeywordExtractionTableName: !GetAtt StorageStack.Outputs.TranscriptionKeywordExtractionTableName
        LiveCallsMetadataTableName: !GetAtt StorageStack.Outputs.LiveCallsMetadataTableName
        MergedRecordingBucketARN: !GetAtt StorageStack.Outputs.MergedRecordingBucketARN
        TranscriptionKeywordExtractionTableARN: !GetAtt StorageStack.Outputs.TranscriptionKeywordExtractionTableARN
        LiveCallsMetadataTableARN: !GetAtt StorageStack.Outputs.LiveCallsMetadataTableARN
        MinCapacity: !Ref MinCapacity
        MaxCapacity: !Ref MaxCapacity
        DesiredCapacity: !Ref DesiredCapacity
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        BastionSecurityGroupId: !Ref BastionSecurityGroupId

Outputs:
  RecordingBucket:
    Description: The Name of Audio Recording Bucket
    Value: !GetAtt StorageStack.Outputs.RecordingBucketName

  MergedRecordingBucket:
    Description: The Name of Merged Recording Bucket
    Value: !GetAtt StorageStack.Outputs.MergedRecordingBucketName

  SourceArtifactBucket:
    Description: The Name of Source Artifact Bucket
    Value: !GetAtt StorageStack.Outputs.SourceArtifactBucketName
 
  LiveCallsTranscriptionTable:
    Description: Transcription table
    Value: !GetAtt StorageStack.Outputs.LiveCallsTranscriptionTableName
 
  LiveCallsMetadataTable:
    Description: Live Call MetaData table
    Value: !GetAtt StorageStack.Outputs.LiveCallsMetadataTableName

  TranscriptionWebsocketConnectionTable:
    Description: The name of Connection table
    Value: !GetAtt StorageStack.Outputs.TranscriptionWebsocketConnectionTableName

  TranscriptionKeywordExtractionTable:
    Description: The name of Keywords table
    Value: !GetAtt StorageStack.Outputs.TranscriptionKeywordExtractionTableName

  LoadBalancerDNSAddr:
    Description: DNS Address of the Load-Balancer
    Value: !GetAtt WebAppDeploymentStack.Outputs.LoadBalancerDNS
